erDiagram
    USER ||--o| PROFILE : "has"
    USER ||--o{ ADOPTED_TREE : "(sponsor) owns"
    USER ||--o{ TREE_LOG : "(admin) create"
    
    PROFILE ||--o{ TRANSACTION : "executes"
    
    TRANSACTION ||--o| PAYMENT : "generates"
    TRANSACTION }o--|| ADOPTED_TREE : "targets"
    
    ADOPTED_TREE }o--|| TREE_SPECIES : "is species"
    ADOPTED_TREE }o--|| FOREST_PLOT : "planted in"
    ADOPTED_TREE ||--o{ TREE_LOG : "has history"

    USER {
        uuid id PK
        string email
        string password_hash
        string role_type "ADMIN | SPONSOR"
    }

    PROFILE {
        uuid id PK "FK to User.id"
        string full_name
        date date_of_birth
        int age
        int balance
    }

    PAYMENT {
        uuid id PK
        uuid transaction_id FK
        int amount
        string status "PENDING | FINISHED | FAILED | EXPIRED"
        string external_id
        timestamp created_at
    }

    TRANSACTION {
        uuid id PK
        uuid profile_id FK
        uuid adopted_tree_id FK
        int amount
        string type
        timestamp transaction_date
    }

    FOREST_PLOT {
        uuid id PK
        string location_name
        string address
        float available_space_m2
    }

    TREE_SPECIES {
        uuid id PK
        string common_name
        float space_required_m2
        int price
    }

    ADOPTED_TREE {
        uuid id PK
        uuid user_id FK
        uuid species_id FK
        uuid plot_id FK
        string custom_name
        float initial_height_meters
        timestamp last_care_date
        timestamp adopted_at
    }

    TREE_LOG {
        uuid id PK
        uuid adopted_tree_id FK
        uuid admin_id FK
        float current_height_meters
        string activity
        string note
        timestamp created_at
    }