// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/finance-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_DEPOSIT    TransactionType = 0
	TransactionType_WITHDRAWAL TransactionType = 1
	TransactionType_PURCHASE   TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "DEPOSIT",
		1: "WITHDRAWAL",
		2: "PURCHASE",
	}
	TransactionType_value = map[string]int32{
		"DEPOSIT":    0,
		"WITHDRAWAL": 1,
		"PURCHASE":   2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_finance_service_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_finance_service_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{0}
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=finance.TransactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_finance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_DEPOSIT
}

type TopUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpRequest) Reset() {
	*x = TopUpRequest{}
	mi := &file_proto_finance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpRequest) ProtoMessage() {}

func (x *TopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpRequest.ProtoReflect.Descriptor instead.
func (*TopUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{1}
}

func (x *TopUpRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,4,opt,name=type,proto3,enum=finance.TransactionType" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_finance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_DEPOSIT
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TransactionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionList) Reset() {
	*x = TransactionList{}
	mi := &file_proto_finance_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionList) ProtoMessage() {}

func (x *TransactionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionList.ProtoReflect.Descriptor instead.
func (*TransactionList) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionList) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type PaymentUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentUrlResponse) Reset() {
	*x = PaymentUrlResponse{}
	mi := &file_proto_finance_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentUrlResponse) ProtoMessage() {}

func (x *PaymentUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentUrlResponse.ProtoReflect.Descriptor instead.
func (*PaymentUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_proto_finance_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type WebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Generic payload from Xendit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookRequest) Reset() {
	*x = WebhookRequest{}
	mi := &file_proto_finance_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookRequest) ProtoMessage() {}

func (x *WebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookRequest.ProtoReflect.Descriptor instead.
func (*WebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_finance_service_proto_rawDescGZIP(), []int{6}
}

func (x *WebhookRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *WebhookRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_finance_service_proto protoreflect.FileDescriptor

const file_proto_finance_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/finance-service.proto\x12\afinance\x1a\x1bgoogle/protobuf/empty.proto\"s\n" +
	"\x12TransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.finance.TransactionTypeR\x04type\"&\n" +
	"\fTopUpRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\"\x94\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.finance.TransactionTypeR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"K\n" +
	"\x0fTransactionList\x128\n" +
	"\ftransactions\x18\x01 \x03(\v2\x14.finance.TransactionR\ftransactions\"&\n" +
	"\x12PaymentUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"+\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\":\n" +
	"\x0eWebhookRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*<\n" +
	"\x0fTransactionType\x12\v\n" +
	"\aDEPOSIT\x10\x00\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\x01\x12\f\n" +
	"\bPURCHASE\x10\x022\xb4\x03\n" +
	"\x0eFinanceService\x12F\n" +
	"\x11CreateTransaction\x12\x1b.finance.TransactionRequest\x1a\x14.finance.Transaction\x12A\n" +
	"\vTopUpWallet\x12\x15.finance.TopUpRequest\x1a\x1b.finance.PaymentUrlResponse\x12F\n" +
	"\x13HandleWalletWebhook\x12\x17.finance.WebhookRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"GetBalance\x12\x16.google.protobuf.Empty\x1a\x18.finance.BalanceResponse\x12I\n" +
	"\x15GetTransactionHistory\x12\x16.google.protobuf.Empty\x1a\x18.finance.TransactionList\x12D\n" +
	"\x12CheckPaymentExpiry\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x11Z\x0freforest/pkg/pbb\x06proto3"

var (
	file_proto_finance_service_proto_rawDescOnce sync.Once
	file_proto_finance_service_proto_rawDescData []byte
)

func file_proto_finance_service_proto_rawDescGZIP() []byte {
	file_proto_finance_service_proto_rawDescOnce.Do(func() {
		file_proto_finance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finance_service_proto_rawDesc), len(file_proto_finance_service_proto_rawDesc)))
	})
	return file_proto_finance_service_proto_rawDescData
}

var file_proto_finance_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_finance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_finance_service_proto_goTypes = []any{
	(TransactionType)(0),       // 0: finance.TransactionType
	(*TransactionRequest)(nil), // 1: finance.TransactionRequest
	(*TopUpRequest)(nil),       // 2: finance.TopUpRequest
	(*Transaction)(nil),        // 3: finance.Transaction
	(*TransactionList)(nil),    // 4: finance.TransactionList
	(*PaymentUrlResponse)(nil), // 5: finance.PaymentUrlResponse
	(*BalanceResponse)(nil),    // 6: finance.BalanceResponse
	(*WebhookRequest)(nil),     // 7: finance.WebhookRequest
	(*emptypb.Empty)(nil),      // 8: google.protobuf.Empty
}
var file_proto_finance_service_proto_depIdxs = []int32{
	0, // 0: finance.TransactionRequest.type:type_name -> finance.TransactionType
	0, // 1: finance.Transaction.type:type_name -> finance.TransactionType
	3, // 2: finance.TransactionList.transactions:type_name -> finance.Transaction
	1, // 3: finance.FinanceService.CreateTransaction:input_type -> finance.TransactionRequest
	2, // 4: finance.FinanceService.TopUpWallet:input_type -> finance.TopUpRequest
	7, // 5: finance.FinanceService.HandleWalletWebhook:input_type -> finance.WebhookRequest
	8, // 6: finance.FinanceService.GetBalance:input_type -> google.protobuf.Empty
	8, // 7: finance.FinanceService.GetTransactionHistory:input_type -> google.protobuf.Empty
	8, // 8: finance.FinanceService.CheckPaymentExpiry:input_type -> google.protobuf.Empty
	3, // 9: finance.FinanceService.CreateTransaction:output_type -> finance.Transaction
	5, // 10: finance.FinanceService.TopUpWallet:output_type -> finance.PaymentUrlResponse
	8, // 11: finance.FinanceService.HandleWalletWebhook:output_type -> google.protobuf.Empty
	6, // 12: finance.FinanceService.GetBalance:output_type -> finance.BalanceResponse
	4, // 13: finance.FinanceService.GetTransactionHistory:output_type -> finance.TransactionList
	8, // 14: finance.FinanceService.CheckPaymentExpiry:output_type -> google.protobuf.Empty
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_finance_service_proto_init() }
func file_proto_finance_service_proto_init() {
	if File_proto_finance_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finance_service_proto_rawDesc), len(file_proto_finance_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finance_service_proto_goTypes,
		DependencyIndexes: file_proto_finance_service_proto_depIdxs,
		EnumInfos:         file_proto_finance_service_proto_enumTypes,
		MessageInfos:      file_proto_finance_service_proto_msgTypes,
	}.Build()
	File_proto_finance_service_proto = out.File
	file_proto_finance_service_proto_goTypes = nil
	file_proto_finance_service_proto_depIdxs = nil
}
