// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tree-management-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_proto_tree_management_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Species struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommonName      string                 `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	SpaceRequiredM2 float32                `protobuf:"fixed32,3,opt,name=space_required_m2,json=spaceRequiredM2,proto3" json:"space_required_m2,omitempty"`
	Price           int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Species) Reset() {
	*x = Species{}
	mi := &file_proto_tree_management_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Species) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Species) ProtoMessage() {}

func (x *Species) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Species.ProtoReflect.Descriptor instead.
func (*Species) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{1}
}

func (x *Species) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Species) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Species) GetSpaceRequiredM2() float32 {
	if x != nil {
		return x.SpaceRequiredM2
	}
	return 0
}

func (x *Species) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SpeciesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Species       []*Species             `protobuf:"bytes,1,rep,name=species,proto3" json:"species,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeciesList) Reset() {
	*x = SpeciesList{}
	mi := &file_proto_tree_management_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeciesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeciesList) ProtoMessage() {}

func (x *SpeciesList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeciesList.ProtoReflect.Descriptor instead.
func (*SpeciesList) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{2}
}

func (x *SpeciesList) GetSpecies() []*Species {
	if x != nil {
		return x.Species
	}
	return nil
}

type Plot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationName     string                 `protobuf:"bytes,2,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AvailableSpaceM2 float32                `protobuf:"fixed32,4,opt,name=available_space_m2,json=availableSpaceM2,proto3" json:"available_space_m2,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Plot) Reset() {
	*x = Plot{}
	mi := &file_proto_tree_management_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plot) ProtoMessage() {}

func (x *Plot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plot.ProtoReflect.Descriptor instead.
func (*Plot) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{3}
}

func (x *Plot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Plot) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *Plot) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Plot) GetAvailableSpaceM2() float32 {
	if x != nil {
		return x.AvailableSpaceM2
	}
	return 0
}

type PlotList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plots         []*Plot                `protobuf:"bytes,1,rep,name=plots,proto3" json:"plots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotList) Reset() {
	*x = PlotList{}
	mi := &file_proto_tree_management_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotList) ProtoMessage() {}

func (x *PlotList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotList.ProtoReflect.Descriptor instead.
func (*PlotList) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{4}
}

func (x *PlotList) GetPlots() []*Plot {
	if x != nil {
		return x.Plots
	}
	return nil
}

type Tree struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SponsorId           string                 `protobuf:"bytes,2,opt,name=sponsor_id,json=sponsorId,proto3" json:"sponsor_id,omitempty"`
	SpeciesId           string                 `protobuf:"bytes,3,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"`
	PlotId              string                 `protobuf:"bytes,4,opt,name=plot_id,json=plotId,proto3" json:"plot_id,omitempty"`
	CustomName          string                 `protobuf:"bytes,5,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	CurrentHeightMeters float32                `protobuf:"fixed32,6,opt,name=current_height_meters,json=currentHeightMeters,proto3" json:"current_height_meters,omitempty"`
	TotalFundedLifetime int32                  `protobuf:"varint,7,opt,name=total_funded_lifetime,json=totalFundedLifetime,proto3" json:"total_funded_lifetime,omitempty"`
	LastCareDate        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_care_date,json=lastCareDate,proto3" json:"last_care_date,omitempty"`
	AdoptedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=adopted_at,json=adoptedAt,proto3" json:"adopted_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_proto_tree_management_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{5}
}

func (x *Tree) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tree) GetSponsorId() string {
	if x != nil {
		return x.SponsorId
	}
	return ""
}

func (x *Tree) GetSpeciesId() string {
	if x != nil {
		return x.SpeciesId
	}
	return ""
}

func (x *Tree) GetPlotId() string {
	if x != nil {
		return x.PlotId
	}
	return ""
}

func (x *Tree) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *Tree) GetCurrentHeightMeters() float32 {
	if x != nil {
		return x.CurrentHeightMeters
	}
	return 0
}

func (x *Tree) GetTotalFundedLifetime() int32 {
	if x != nil {
		return x.TotalFundedLifetime
	}
	return 0
}

func (x *Tree) GetLastCareDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCareDate
	}
	return nil
}

func (x *Tree) GetAdoptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AdoptedAt
	}
	return nil
}

type TreeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trees         []*Tree                `protobuf:"bytes,1,rep,name=trees,proto3" json:"trees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeList) Reset() {
	*x = TreeList{}
	mi := &file_proto_tree_management_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeList) ProtoMessage() {}

func (x *TreeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeList.ProtoReflect.Descriptor instead.
func (*TreeList) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{6}
}

func (x *TreeList) GetTrees() []*Tree {
	if x != nil {
		return x.Trees
	}
	return nil
}

type AdoptTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeciesId     string                 `protobuf:"bytes,1,opt,name=species_id,json=speciesId,proto3" json:"species_id,omitempty"`
	PlotId        string                 `protobuf:"bytes,2,opt,name=plot_id,json=plotId,proto3" json:"plot_id,omitempty"`
	CustomName    string                 `protobuf:"bytes,3,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptTreeRequest) Reset() {
	*x = AdoptTreeRequest{}
	mi := &file_proto_tree_management_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptTreeRequest) ProtoMessage() {}

func (x *AdoptTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptTreeRequest.ProtoReflect.Descriptor instead.
func (*AdoptTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{7}
}

func (x *AdoptTreeRequest) GetSpeciesId() string {
	if x != nil {
		return x.SpeciesId
	}
	return ""
}

func (x *AdoptTreeRequest) GetPlotId() string {
	if x != nil {
		return x.PlotId
	}
	return ""
}

func (x *AdoptTreeRequest) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

type AdoptTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeId        string                 `protobuf:"bytes,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptTreeResponse) Reset() {
	*x = AdoptTreeResponse{}
	mi := &file_proto_tree_management_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptTreeResponse) ProtoMessage() {}

func (x *AdoptTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptTreeResponse.ProtoReflect.Descriptor instead.
func (*AdoptTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{8}
}

func (x *AdoptTreeResponse) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *AdoptTreeResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type LogEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdoptedTreeId       string                 `protobuf:"bytes,2,opt,name=adopted_tree_id,json=adoptedTreeId,proto3" json:"adopted_tree_id,omitempty"`
	AdminId             string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	CurrentHeightMeters float32                `protobuf:"fixed32,4,opt,name=current_height_meters,json=currentHeightMeters,proto3" json:"current_height_meters,omitempty"`
	Activity            string                 `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Note                string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	RecordedAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_tree_management_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{9}
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetAdoptedTreeId() string {
	if x != nil {
		return x.AdoptedTreeId
	}
	return ""
}

func (x *LogEntry) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *LogEntry) GetCurrentHeightMeters() float32 {
	if x != nil {
		return x.CurrentHeightMeters
	}
	return 0
}

func (x *LogEntry) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *LogEntry) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *LogEntry) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type CreateLogRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AdoptedTreeId       string                 `protobuf:"bytes,1,opt,name=adopted_tree_id,json=adoptedTreeId,proto3" json:"adopted_tree_id,omitempty"`
	CurrentHeightMeters float32                `protobuf:"fixed32,2,opt,name=current_height_meters,json=currentHeightMeters,proto3" json:"current_height_meters,omitempty"`
	Activity            string                 `protobuf:"bytes,3,opt,name=activity,proto3" json:"activity,omitempty"`
	Note                string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateLogRequest) Reset() {
	*x = CreateLogRequest{}
	mi := &file_proto_tree_management_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLogRequest) ProtoMessage() {}

func (x *CreateLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLogRequest.ProtoReflect.Descriptor instead.
func (*CreateLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateLogRequest) GetAdoptedTreeId() string {
	if x != nil {
		return x.AdoptedTreeId
	}
	return ""
}

func (x *CreateLogRequest) GetCurrentHeightMeters() float32 {
	if x != nil {
		return x.CurrentHeightMeters
	}
	return 0
}

func (x *CreateLogRequest) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *CreateLogRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type LogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogList) Reset() {
	*x = LogList{}
	mi := &file_proto_tree_management_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogList) ProtoMessage() {}

func (x *LogList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tree_management_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogList.ProtoReflect.Descriptor instead.
func (*LogList) Descriptor() ([]byte, []int) {
	return file_proto_tree_management_service_proto_rawDescGZIP(), []int{11}
}

func (x *LogList) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_proto_tree_management_service_proto protoreflect.FileDescriptor

const file_proto_tree_management_service_proto_rawDesc = "" +
	"\n" +
	"#proto/tree-management-service.proto\x12\x04tree\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"|\n" +
	"\aSpecies\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcommon_name\x18\x02 \x01(\tR\n" +
	"commonName\x12*\n" +
	"\x11space_required_m2\x18\x03 \x01(\x02R\x0fspaceRequiredM2\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\"6\n" +
	"\vSpeciesList\x12'\n" +
	"\aspecies\x18\x01 \x03(\v2\r.tree.SpeciesR\aspecies\"\x83\x01\n" +
	"\x04Plot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rlocation_name\x18\x02 \x01(\tR\flocationName\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12,\n" +
	"\x12available_space_m2\x18\x04 \x01(\x02R\x10availableSpaceM2\",\n" +
	"\bPlotList\x12 \n" +
	"\x05plots\x18\x01 \x03(\v2\n" +
	".tree.PlotR\x05plots\"\xf3\x02\n" +
	"\x04Tree\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sponsor_id\x18\x02 \x01(\tR\tsponsorId\x12\x1d\n" +
	"\n" +
	"species_id\x18\x03 \x01(\tR\tspeciesId\x12\x17\n" +
	"\aplot_id\x18\x04 \x01(\tR\x06plotId\x12\x1f\n" +
	"\vcustom_name\x18\x05 \x01(\tR\n" +
	"customName\x122\n" +
	"\x15current_height_meters\x18\x06 \x01(\x02R\x13currentHeightMeters\x122\n" +
	"\x15total_funded_lifetime\x18\a \x01(\x05R\x13totalFundedLifetime\x12@\n" +
	"\x0elast_care_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastCareDate\x129\n" +
	"\n" +
	"adopted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tadoptedAt\",\n" +
	"\bTreeList\x12 \n" +
	"\x05trees\x18\x01 \x03(\v2\n" +
	".tree.TreeR\x05trees\"k\n" +
	"\x10AdoptTreeRequest\x12\x1d\n" +
	"\n" +
	"species_id\x18\x01 \x01(\tR\tspeciesId\x12\x17\n" +
	"\aplot_id\x18\x02 \x01(\tR\x06plotId\x12\x1f\n" +
	"\vcustom_name\x18\x03 \x01(\tR\n" +
	"customName\"M\n" +
	"\x11AdoptTreeResponse\x12\x17\n" +
	"\atree_id\x18\x01 \x01(\tR\x06treeId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\"\xfe\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fadopted_tree_id\x18\x02 \x01(\tR\radoptedTreeId\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\x122\n" +
	"\x15current_height_meters\x18\x04 \x01(\x02R\x13currentHeightMeters\x12\x1a\n" +
	"\bactivity\x18\x05 \x01(\tR\bactivity\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12;\n" +
	"\vrecorded_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"\x9e\x01\n" +
	"\x10CreateLogRequest\x12&\n" +
	"\x0fadopted_tree_id\x18\x01 \x01(\tR\radoptedTreeId\x122\n" +
	"\x15current_height_meters\x18\x02 \x01(\x02R\x13currentHeightMeters\x12\x1a\n" +
	"\bactivity\x18\x03 \x01(\tR\bactivity\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"-\n" +
	"\aLogList\x12\"\n" +
	"\x04logs\x18\x01 \x03(\v2\x0e.tree.LogEntryR\x04logs2\xfa\a\n" +
	"\vTreeService\x128\n" +
	"\vListSpecies\x12\x16.google.protobuf.Empty\x1a\x11.tree.SpeciesList\x12,\n" +
	"\n" +
	"GetSpecies\x12\x0f.tree.IdRequest\x1a\r.tree.Species\x12-\n" +
	"\rCreateSpecies\x12\r.tree.Species\x1a\r.tree.Species\x12-\n" +
	"\rUpdateSpecies\x12\r.tree.Species\x1a\r.tree.Species\x128\n" +
	"\rDeleteSpecies\x12\x0f.tree.IdRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\tListPlots\x12\x16.google.protobuf.Empty\x1a\x0e.tree.PlotList\x12&\n" +
	"\aGetPlot\x12\x0f.tree.IdRequest\x1a\n" +
	".tree.Plot\x12$\n" +
	"\n" +
	"CreatePlot\x12\n" +
	".tree.Plot\x1a\n" +
	".tree.Plot\x12$\n" +
	"\n" +
	"UpdatePlot\x12\n" +
	".tree.Plot\x1a\n" +
	".tree.Plot\x125\n" +
	"\n" +
	"DeletePlot\x12\x0f.tree.IdRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\tListTrees\x12\x16.google.protobuf.Empty\x1a\x0e.tree.TreeList\x12<\n" +
	"\tAdoptTree\x12\x16.tree.AdoptTreeRequest\x1a\x17.tree.AdoptTreeResponse\x12&\n" +
	"\aGetTree\x12\x0f.tree.IdRequest\x1a\n" +
	".tree.Tree\x12$\n" +
	"\n" +
	"UpdateTree\x12\n" +
	".tree.Tree\x1a\n" +
	".tree.Tree\x125\n" +
	"\n" +
	"DeleteTree\x12\x0f.tree.IdRequest\x1a\x16.google.protobuf.Empty\x12-\n" +
	"\vGetTreeLogs\x12\x0f.tree.IdRequest\x1a\r.tree.LogList\x123\n" +
	"\tCreateLog\x12\x16.tree.CreateLogRequest\x1a\x0e.tree.LogEntry\x12+\n" +
	"\tUpdateLog\x12\x0e.tree.LogEntry\x1a\x0e.tree.LogEntry\x124\n" +
	"\tDeleteLog\x12\x0f.tree.IdRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x1aTriggerBiweeklyMaintenance\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x11Z\x0freforest/pkg/pbb\x06proto3"

var (
	file_proto_tree_management_service_proto_rawDescOnce sync.Once
	file_proto_tree_management_service_proto_rawDescData []byte
)

func file_proto_tree_management_service_proto_rawDescGZIP() []byte {
	file_proto_tree_management_service_proto_rawDescOnce.Do(func() {
		file_proto_tree_management_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tree_management_service_proto_rawDesc), len(file_proto_tree_management_service_proto_rawDesc)))
	})
	return file_proto_tree_management_service_proto_rawDescData
}

var file_proto_tree_management_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_tree_management_service_proto_goTypes = []any{
	(*IdRequest)(nil),             // 0: tree.IdRequest
	(*Species)(nil),               // 1: tree.Species
	(*SpeciesList)(nil),           // 2: tree.SpeciesList
	(*Plot)(nil),                  // 3: tree.Plot
	(*PlotList)(nil),              // 4: tree.PlotList
	(*Tree)(nil),                  // 5: tree.Tree
	(*TreeList)(nil),              // 6: tree.TreeList
	(*AdoptTreeRequest)(nil),      // 7: tree.AdoptTreeRequest
	(*AdoptTreeResponse)(nil),     // 8: tree.AdoptTreeResponse
	(*LogEntry)(nil),              // 9: tree.LogEntry
	(*CreateLogRequest)(nil),      // 10: tree.CreateLogRequest
	(*LogList)(nil),               // 11: tree.LogList
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_proto_tree_management_service_proto_depIdxs = []int32{
	1,  // 0: tree.SpeciesList.species:type_name -> tree.Species
	3,  // 1: tree.PlotList.plots:type_name -> tree.Plot
	12, // 2: tree.Tree.last_care_date:type_name -> google.protobuf.Timestamp
	12, // 3: tree.Tree.adopted_at:type_name -> google.protobuf.Timestamp
	5,  // 4: tree.TreeList.trees:type_name -> tree.Tree
	12, // 5: tree.LogEntry.recorded_at:type_name -> google.protobuf.Timestamp
	9,  // 6: tree.LogList.logs:type_name -> tree.LogEntry
	13, // 7: tree.TreeService.ListSpecies:input_type -> google.protobuf.Empty
	0,  // 8: tree.TreeService.GetSpecies:input_type -> tree.IdRequest
	1,  // 9: tree.TreeService.CreateSpecies:input_type -> tree.Species
	1,  // 10: tree.TreeService.UpdateSpecies:input_type -> tree.Species
	0,  // 11: tree.TreeService.DeleteSpecies:input_type -> tree.IdRequest
	13, // 12: tree.TreeService.ListPlots:input_type -> google.protobuf.Empty
	0,  // 13: tree.TreeService.GetPlot:input_type -> tree.IdRequest
	3,  // 14: tree.TreeService.CreatePlot:input_type -> tree.Plot
	3,  // 15: tree.TreeService.UpdatePlot:input_type -> tree.Plot
	0,  // 16: tree.TreeService.DeletePlot:input_type -> tree.IdRequest
	13, // 17: tree.TreeService.ListTrees:input_type -> google.protobuf.Empty
	7,  // 18: tree.TreeService.AdoptTree:input_type -> tree.AdoptTreeRequest
	0,  // 19: tree.TreeService.GetTree:input_type -> tree.IdRequest
	5,  // 20: tree.TreeService.UpdateTree:input_type -> tree.Tree
	0,  // 21: tree.TreeService.DeleteTree:input_type -> tree.IdRequest
	0,  // 22: tree.TreeService.GetTreeLogs:input_type -> tree.IdRequest
	10, // 23: tree.TreeService.CreateLog:input_type -> tree.CreateLogRequest
	9,  // 24: tree.TreeService.UpdateLog:input_type -> tree.LogEntry
	0,  // 25: tree.TreeService.DeleteLog:input_type -> tree.IdRequest
	13, // 26: tree.TreeService.TriggerBiweeklyMaintenance:input_type -> google.protobuf.Empty
	2,  // 27: tree.TreeService.ListSpecies:output_type -> tree.SpeciesList
	1,  // 28: tree.TreeService.GetSpecies:output_type -> tree.Species
	1,  // 29: tree.TreeService.CreateSpecies:output_type -> tree.Species
	1,  // 30: tree.TreeService.UpdateSpecies:output_type -> tree.Species
	13, // 31: tree.TreeService.DeleteSpecies:output_type -> google.protobuf.Empty
	4,  // 32: tree.TreeService.ListPlots:output_type -> tree.PlotList
	3,  // 33: tree.TreeService.GetPlot:output_type -> tree.Plot
	3,  // 34: tree.TreeService.CreatePlot:output_type -> tree.Plot
	3,  // 35: tree.TreeService.UpdatePlot:output_type -> tree.Plot
	13, // 36: tree.TreeService.DeletePlot:output_type -> google.protobuf.Empty
	6,  // 37: tree.TreeService.ListTrees:output_type -> tree.TreeList
	8,  // 38: tree.TreeService.AdoptTree:output_type -> tree.AdoptTreeResponse
	5,  // 39: tree.TreeService.GetTree:output_type -> tree.Tree
	5,  // 40: tree.TreeService.UpdateTree:output_type -> tree.Tree
	13, // 41: tree.TreeService.DeleteTree:output_type -> google.protobuf.Empty
	11, // 42: tree.TreeService.GetTreeLogs:output_type -> tree.LogList
	9,  // 43: tree.TreeService.CreateLog:output_type -> tree.LogEntry
	9,  // 44: tree.TreeService.UpdateLog:output_type -> tree.LogEntry
	13, // 45: tree.TreeService.DeleteLog:output_type -> google.protobuf.Empty
	13, // 46: tree.TreeService.TriggerBiweeklyMaintenance:output_type -> google.protobuf.Empty
	27, // [27:47] is the sub-list for method output_type
	7,  // [7:27] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_tree_management_service_proto_init() }
func file_proto_tree_management_service_proto_init() {
	if File_proto_tree_management_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tree_management_service_proto_rawDesc), len(file_proto_tree_management_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tree_management_service_proto_goTypes,
		DependencyIndexes: file_proto_tree_management_service_proto_depIdxs,
		MessageInfos:      file_proto_tree_management_service_proto_msgTypes,
	}.Build()
	File_proto_tree_management_service_proto = out.File
	file_proto_tree_management_service_proto_goTypes = nil
	file_proto_tree_management_service_proto_depIdxs = nil
}
