// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/tree-management-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TreeService_ListSpecies_FullMethodName                = "/tree.TreeService/ListSpecies"
	TreeService_GetSpecies_FullMethodName                 = "/tree.TreeService/GetSpecies"
	TreeService_CreateSpecies_FullMethodName              = "/tree.TreeService/CreateSpecies"
	TreeService_UpdateSpecies_FullMethodName              = "/tree.TreeService/UpdateSpecies"
	TreeService_DeleteSpecies_FullMethodName              = "/tree.TreeService/DeleteSpecies"
	TreeService_ListPlots_FullMethodName                  = "/tree.TreeService/ListPlots"
	TreeService_GetPlot_FullMethodName                    = "/tree.TreeService/GetPlot"
	TreeService_CreatePlot_FullMethodName                 = "/tree.TreeService/CreatePlot"
	TreeService_UpdatePlot_FullMethodName                 = "/tree.TreeService/UpdatePlot"
	TreeService_DeletePlot_FullMethodName                 = "/tree.TreeService/DeletePlot"
	TreeService_ListTrees_FullMethodName                  = "/tree.TreeService/ListTrees"
	TreeService_AdoptTree_FullMethodName                  = "/tree.TreeService/AdoptTree"
	TreeService_GetTree_FullMethodName                    = "/tree.TreeService/GetTree"
	TreeService_UpdateTree_FullMethodName                 = "/tree.TreeService/UpdateTree"
	TreeService_DeleteTree_FullMethodName                 = "/tree.TreeService/DeleteTree"
	TreeService_GetTreeLogs_FullMethodName                = "/tree.TreeService/GetTreeLogs"
	TreeService_CreateLog_FullMethodName                  = "/tree.TreeService/CreateLog"
	TreeService_UpdateLog_FullMethodName                  = "/tree.TreeService/UpdateLog"
	TreeService_DeleteLog_FullMethodName                  = "/tree.TreeService/DeleteLog"
	TreeService_TriggerBiweeklyMaintenance_FullMethodName = "/tree.TreeService/TriggerBiweeklyMaintenance"
)

// TreeServiceClient is the client API for TreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeServiceClient interface {
	// Species
	ListSpecies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpeciesList, error)
	GetSpecies(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Species, error)
	CreateSpecies(ctx context.Context, in *Species, opts ...grpc.CallOption) (*Species, error)
	UpdateSpecies(ctx context.Context, in *Species, opts ...grpc.CallOption) (*Species, error)
	DeleteSpecies(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Plots
	ListPlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlotList, error)
	GetPlot(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Plot, error)
	CreatePlot(ctx context.Context, in *Plot, opts ...grpc.CallOption) (*Plot, error)
	UpdatePlot(ctx context.Context, in *Plot, opts ...grpc.CallOption) (*Plot, error)
	DeletePlot(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Trees
	ListTrees(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TreeList, error)
	AdoptTree(ctx context.Context, in *AdoptTreeRequest, opts ...grpc.CallOption) (*AdoptTreeResponse, error)
	GetTree(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Tree, error)
	UpdateTree(ctx context.Context, in *Tree, opts ...grpc.CallOption) (*Tree, error)
	DeleteTree(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Logs
	GetTreeLogs(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LogList, error)
	CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*LogEntry, error)
	UpdateLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogEntry, error)
	DeleteLog(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Scheduled Jobs
	TriggerBiweeklyMaintenance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type treeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeServiceClient(cc grpc.ClientConnInterface) TreeServiceClient {
	return &treeServiceClient{cc}
}

func (c *treeServiceClient) ListSpecies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpeciesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeciesList)
	err := c.cc.Invoke(ctx, TreeService_ListSpecies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetSpecies(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Species, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Species)
	err := c.cc.Invoke(ctx, TreeService_GetSpecies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) CreateSpecies(ctx context.Context, in *Species, opts ...grpc.CallOption) (*Species, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Species)
	err := c.cc.Invoke(ctx, TreeService_CreateSpecies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) UpdateSpecies(ctx context.Context, in *Species, opts ...grpc.CallOption) (*Species, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Species)
	err := c.cc.Invoke(ctx, TreeService_UpdateSpecies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) DeleteSpecies(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TreeService_DeleteSpecies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) ListPlots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlotList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlotList)
	err := c.cc.Invoke(ctx, TreeService_ListPlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetPlot(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Plot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plot)
	err := c.cc.Invoke(ctx, TreeService_GetPlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) CreatePlot(ctx context.Context, in *Plot, opts ...grpc.CallOption) (*Plot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plot)
	err := c.cc.Invoke(ctx, TreeService_CreatePlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) UpdatePlot(ctx context.Context, in *Plot, opts ...grpc.CallOption) (*Plot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plot)
	err := c.cc.Invoke(ctx, TreeService_UpdatePlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) DeletePlot(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TreeService_DeletePlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) ListTrees(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TreeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeList)
	err := c.cc.Invoke(ctx, TreeService_ListTrees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) AdoptTree(ctx context.Context, in *AdoptTreeRequest, opts ...grpc.CallOption) (*AdoptTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptTreeResponse)
	err := c.cc.Invoke(ctx, TreeService_AdoptTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetTree(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, TreeService_GetTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) UpdateTree(ctx context.Context, in *Tree, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, TreeService_UpdateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) DeleteTree(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TreeService_DeleteTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetTreeLogs(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*LogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogList)
	err := c.cc.Invoke(ctx, TreeService_GetTreeLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) CreateLog(ctx context.Context, in *CreateLogRequest, opts ...grpc.CallOption) (*LogEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogEntry)
	err := c.cc.Invoke(ctx, TreeService_CreateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) UpdateLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogEntry)
	err := c.cc.Invoke(ctx, TreeService_UpdateLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) DeleteLog(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TreeService_DeleteLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) TriggerBiweeklyMaintenance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TreeService_TriggerBiweeklyMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeServiceServer is the server API for TreeService service.
// All implementations must embed UnimplementedTreeServiceServer
// for forward compatibility.
type TreeServiceServer interface {
	// Species
	ListSpecies(context.Context, *emptypb.Empty) (*SpeciesList, error)
	GetSpecies(context.Context, *IdRequest) (*Species, error)
	CreateSpecies(context.Context, *Species) (*Species, error)
	UpdateSpecies(context.Context, *Species) (*Species, error)
	DeleteSpecies(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Plots
	ListPlots(context.Context, *emptypb.Empty) (*PlotList, error)
	GetPlot(context.Context, *IdRequest) (*Plot, error)
	CreatePlot(context.Context, *Plot) (*Plot, error)
	UpdatePlot(context.Context, *Plot) (*Plot, error)
	DeletePlot(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Trees
	ListTrees(context.Context, *emptypb.Empty) (*TreeList, error)
	AdoptTree(context.Context, *AdoptTreeRequest) (*AdoptTreeResponse, error)
	GetTree(context.Context, *IdRequest) (*Tree, error)
	UpdateTree(context.Context, *Tree) (*Tree, error)
	DeleteTree(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Logs
	GetTreeLogs(context.Context, *IdRequest) (*LogList, error)
	CreateLog(context.Context, *CreateLogRequest) (*LogEntry, error)
	UpdateLog(context.Context, *LogEntry) (*LogEntry, error)
	DeleteLog(context.Context, *IdRequest) (*emptypb.Empty, error)
	// Scheduled Jobs
	TriggerBiweeklyMaintenance(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedTreeServiceServer()
}

// UnimplementedTreeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreeServiceServer struct{}

func (UnimplementedTreeServiceServer) ListSpecies(context.Context, *emptypb.Empty) (*SpeciesList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpecies not implemented")
}
func (UnimplementedTreeServiceServer) GetSpecies(context.Context, *IdRequest) (*Species, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpecies not implemented")
}
func (UnimplementedTreeServiceServer) CreateSpecies(context.Context, *Species) (*Species, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSpecies not implemented")
}
func (UnimplementedTreeServiceServer) UpdateSpecies(context.Context, *Species) (*Species, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSpecies not implemented")
}
func (UnimplementedTreeServiceServer) DeleteSpecies(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSpecies not implemented")
}
func (UnimplementedTreeServiceServer) ListPlots(context.Context, *emptypb.Empty) (*PlotList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlots not implemented")
}
func (UnimplementedTreeServiceServer) GetPlot(context.Context, *IdRequest) (*Plot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlot not implemented")
}
func (UnimplementedTreeServiceServer) CreatePlot(context.Context, *Plot) (*Plot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlot not implemented")
}
func (UnimplementedTreeServiceServer) UpdatePlot(context.Context, *Plot) (*Plot, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlot not implemented")
}
func (UnimplementedTreeServiceServer) DeletePlot(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlot not implemented")
}
func (UnimplementedTreeServiceServer) ListTrees(context.Context, *emptypb.Empty) (*TreeList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrees not implemented")
}
func (UnimplementedTreeServiceServer) AdoptTree(context.Context, *AdoptTreeRequest) (*AdoptTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdoptTree not implemented")
}
func (UnimplementedTreeServiceServer) GetTree(context.Context, *IdRequest) (*Tree, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedTreeServiceServer) UpdateTree(context.Context, *Tree) (*Tree, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTree not implemented")
}
func (UnimplementedTreeServiceServer) DeleteTree(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTree not implemented")
}
func (UnimplementedTreeServiceServer) GetTreeLogs(context.Context, *IdRequest) (*LogList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTreeLogs not implemented")
}
func (UnimplementedTreeServiceServer) CreateLog(context.Context, *CreateLogRequest) (*LogEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLog not implemented")
}
func (UnimplementedTreeServiceServer) UpdateLog(context.Context, *LogEntry) (*LogEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLog not implemented")
}
func (UnimplementedTreeServiceServer) DeleteLog(context.Context, *IdRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLog not implemented")
}
func (UnimplementedTreeServiceServer) TriggerBiweeklyMaintenance(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerBiweeklyMaintenance not implemented")
}
func (UnimplementedTreeServiceServer) mustEmbedUnimplementedTreeServiceServer() {}
func (UnimplementedTreeServiceServer) testEmbeddedByValue()                     {}

// UnsafeTreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeServiceServer will
// result in compilation errors.
type UnsafeTreeServiceServer interface {
	mustEmbedUnimplementedTreeServiceServer()
}

func RegisterTreeServiceServer(s grpc.ServiceRegistrar, srv TreeServiceServer) {
	// If the following call panics, it indicates UnimplementedTreeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreeService_ServiceDesc, srv)
}

func _TreeService_ListSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).ListSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_ListSpecies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).ListSpecies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetSpecies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetSpecies(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_CreateSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Species)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).CreateSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_CreateSpecies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).CreateSpecies(ctx, req.(*Species))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_UpdateSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Species)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).UpdateSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_UpdateSpecies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).UpdateSpecies(ctx, req.(*Species))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_DeleteSpecies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).DeleteSpecies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_DeleteSpecies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).DeleteSpecies(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_ListPlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).ListPlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_ListPlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).ListPlots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetPlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetPlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetPlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetPlot(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_CreatePlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).CreatePlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_CreatePlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).CreatePlot(ctx, req.(*Plot))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_UpdatePlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).UpdatePlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_UpdatePlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).UpdatePlot(ctx, req.(*Plot))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_DeletePlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).DeletePlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_DeletePlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).DeletePlot(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_ListTrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).ListTrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_ListTrees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).ListTrees(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_AdoptTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).AdoptTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_AdoptTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).AdoptTree(ctx, req.(*AdoptTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetTree(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_UpdateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Tree)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).UpdateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_UpdateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).UpdateTree(ctx, req.(*Tree))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_DeleteTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).DeleteTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_DeleteTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).DeleteTree(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetTreeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetTreeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetTreeLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetTreeLogs(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_CreateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).CreateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_CreateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).CreateLog(ctx, req.(*CreateLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_UpdateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).UpdateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_UpdateLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).UpdateLog(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_DeleteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).DeleteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_DeleteLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).DeleteLog(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_TriggerBiweeklyMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).TriggerBiweeklyMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_TriggerBiweeklyMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).TriggerBiweeklyMaintenance(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeService_ServiceDesc is the grpc.ServiceDesc for TreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tree.TreeService",
	HandlerType: (*TreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSpecies",
			Handler:    _TreeService_ListSpecies_Handler,
		},
		{
			MethodName: "GetSpecies",
			Handler:    _TreeService_GetSpecies_Handler,
		},
		{
			MethodName: "CreateSpecies",
			Handler:    _TreeService_CreateSpecies_Handler,
		},
		{
			MethodName: "UpdateSpecies",
			Handler:    _TreeService_UpdateSpecies_Handler,
		},
		{
			MethodName: "DeleteSpecies",
			Handler:    _TreeService_DeleteSpecies_Handler,
		},
		{
			MethodName: "ListPlots",
			Handler:    _TreeService_ListPlots_Handler,
		},
		{
			MethodName: "GetPlot",
			Handler:    _TreeService_GetPlot_Handler,
		},
		{
			MethodName: "CreatePlot",
			Handler:    _TreeService_CreatePlot_Handler,
		},
		{
			MethodName: "UpdatePlot",
			Handler:    _TreeService_UpdatePlot_Handler,
		},
		{
			MethodName: "DeletePlot",
			Handler:    _TreeService_DeletePlot_Handler,
		},
		{
			MethodName: "ListTrees",
			Handler:    _TreeService_ListTrees_Handler,
		},
		{
			MethodName: "AdoptTree",
			Handler:    _TreeService_AdoptTree_Handler,
		},
		{
			MethodName: "GetTree",
			Handler:    _TreeService_GetTree_Handler,
		},
		{
			MethodName: "UpdateTree",
			Handler:    _TreeService_UpdateTree_Handler,
		},
		{
			MethodName: "DeleteTree",
			Handler:    _TreeService_DeleteTree_Handler,
		},
		{
			MethodName: "GetTreeLogs",
			Handler:    _TreeService_GetTreeLogs_Handler,
		},
		{
			MethodName: "CreateLog",
			Handler:    _TreeService_CreateLog_Handler,
		},
		{
			MethodName: "UpdateLog",
			Handler:    _TreeService_UpdateLog_Handler,
		},
		{
			MethodName: "DeleteLog",
			Handler:    _TreeService_DeleteLog_Handler,
		},
		{
			MethodName: "TriggerBiweeklyMaintenance",
			Handler:    _TreeService_TriggerBiweeklyMaintenance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tree-management-service.proto",
}
